export const ROUTE_PATHS = {
  HOME: '/home',
  CHAT: '/chat',
  PROFILE: '/profile',
  VERIFY_EMAIL: '/verify-email',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  AGE_GATE: '/age-gate',
  CONSENT: '/consent',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  COMMUNITY_GUIDELINES: '/community-guidelines',
}
